  {
    id: 'ch11-end',
    title: '雨天的灯 · 章末',
    subtitle: '雨灯下的湿意靠近',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch11-end.png'),
    video: cgAsset('/videos/cg/cg-ch11-end.webm'),
    storyHint: '第11章结尾',
  },
  {
    id: 'ch12-end',
    title: '旧伞 · 章末',
    subtitle: '伞骨下交叠的影子',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch12-end.png'),
    video: cgAsset('/videos/cg/cg-ch12-end.webm'),
    storyHint: '第12章结尾',
  },
  {
    id: 'ch13-end',
    title: '常客 · 章末',
    subtitle: '酒香里未拆穿的护短',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch13-end.png'),
    video: cgAsset('/videos/cg/cg-ch13-end.webm'),
    storyHint: '第13章结尾',
  },
  {
    id: 'ch14-end',
    title: '账本背面 · 章末',
    subtitle: '后仓灯下的停顿',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch14-end.png'),
    video: cgAsset('/videos/cg/cg-ch14-end.webm'),
    storyHint: '第14章结尾',
  },
  {
    id: 'ch15-end',
    title: '小别 · 章末',
    subtitle: '夜港风里的并肩',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch15-end.png'),
    video: cgAsset('/videos/cg/cg-ch15-end.webm'),
    storyHint: '第15章结尾',
  },
  {
    id: 'ch16-end',
    title: '关店之后 · 章末',
    subtitle: '卸围裙后的领口松扣',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch16-end.png'),
    video: cgAsset('/videos/cg/cg-ch16-end.webm'),
    storyHint: '第16章结尾',
  },
  {
    id: 'ch17-end',
    title: '红酒与借口 · 章末',
    subtitle: '旧回忆贴上现下的体温',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch17-end.png'),
    video: cgAsset('/videos/cg/cg-ch17-end.webm'),
    storyHint: '第17章结尾',
  },
  {
    id: 'ch18-end',
    title: '高二那年 · 章末',
    subtitle: '图书馆闭馆铃后的近',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch18-end.png'),
    video: cgAsset('/videos/cg/cg-ch18-end.webm'),
    storyHint: '第18章结尾',
  },
  {
    id: 'ch19-end',
    title: '卖铺拷问 · 章末',
    subtitle: '冷意底下的热',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch19-end.png'),
    video: cgAsset('/videos/cg/cg-ch19-end.webm'),
    storyHint: '第19章结尾',
  },
  {
    id: 'ch20-end',
    title: '几乎吻上 · 章末',
    subtitle: '几乎吻上的那一秒余温',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch20-end.png'),
    video: cgAsset('/videos/cg/cg-ch20-end.webm'),
    storyHint: '第20章结尾',
  },
  {
    id: 'ch21-end',
    title: '关店夜话 · 章末',
    subtitle: '关店夜话的红酒气',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch21-end.png'),
    video: cgAsset('/videos/cg/cg-ch21-end.webm'),
    storyHint: '第21章结尾',
  },
  {
    id: 'ch22-end',
    title: '湿润的岸 · 章末',
    subtitle: '梦里追上去的雨',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch22-end.png'),
    video: cgAsset('/videos/cg/cg-ch22-end.webm'),
    storyHint: '第22章结尾',
  },
  {
    id: 'ch23-end',
    title: '市集早晨 · 章末',
    subtitle: '市集晨光里的并肩',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch23-end.png'),
    video: cgAsset('/videos/cg/cg-ch23-end.webm'),
    storyHint: '第23章结尾',
  },
  {
    id: 'ch24-end',
    title: '休息日 · 章末',
    subtitle: '防波堤上放慢的脚步',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch24-end.png'),
    video: cgAsset('/videos/cg/cg-ch24-end.webm'),
    storyHint: '第24章结尾',
  },
  {
    id: 'ch25-end',
    title: '清仓 · 章末',
    subtitle: '明信片边角的指尖',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch25-end.png'),
    video: cgAsset('/videos/cg/cg-ch25-end.webm'),
    storyHint: '第25章结尾',
  },
  {
    id: 'ch26-end',
    title: '争吵的边缘 · 章末',
    subtitle: '书架后未说完的气',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch26-end.png'),
    video: cgAsset('/videos/cg/cg-ch26-end.webm'),
    storyHint: '第26章结尾',
  },
  {
    id: 'ch27-end',
    title: '和解的盐 · 章末',
    subtitle: '夜港灯火下的和解',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch27-end.png'),
    video: cgAsset('/videos/cg/cg-ch27-end.webm'),
    storyHint: '第27章结尾',
  },
  {
    id: 'ch28-end',
    title: '谈到很晚 · 章末',
    subtitle: '烛影里的呼吸交叠',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch28-end.png'),
    video: cgAsset('/videos/cg/cg-ch28-end.webm'),
    storyHint: '第28章结尾',
  },
  {
    id: 'ch29-end',
    title: '台风预警 · 章末',
    subtitle: '雨巷尽头的回头',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch29-end.png'),
    video: cgAsset('/videos/cg/cg-ch29-end.webm'),
    storyHint: '第29章结尾',
  },
  {
    id: 'ch30-end',
    title: '来潮声 · 章末',
    subtitle: '湿衣下的体温',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch30-end.png'),
    video: cgAsset('/videos/cg/cg-ch30-end.webm'),
    storyHint: '第30章结尾',
  },
  {
    id: 'ch31-end',
    title: '蜡烛与初版 · 章末',
    subtitle: '地毯上膝碰膝的距离',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch31-end.png'),
    video: cgAsset('/videos/cg/cg-ch31-end.webm'),
    storyHint: '第31章结尾',
  },
  {
    id: 'ch32-end',
    title: '靠得近一点 · 章末',
    subtitle: '外套垫着的那侧地板',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch32-end.png'),
    video: cgAsset('/videos/cg/cg-ch32-end.webm'),
    storyHint: '第32章结尾',
  },
  {
    id: 'ch33-end',
    title: '有没有回头 · 章末',
    subtitle: '诗集脊背上的指腹',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch33-end.png'),
    video: cgAsset('/videos/cg/cg-ch33-end.webm'),
    storyHint: '第33章结尾',
  },
  {
    id: 'ch34-end',
    title: '她先吻上来 · 章末',
    subtitle: '吻住之前的停顿',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch34-end.png'),
    video: cgAsset('/videos/cg/cg-ch34-end.webm'),
    storyHint: '第34章结尾',
  },
  {
    id: 'ch35-end',
    title: '雨困一夜 · 章末',
    subtitle: '雨困夜里的靠岸',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch35-end.png'),
    video: cgAsset('/videos/cg/cg-ch35-end.webm'),
    storyHint: '第35章结尾',
  },
  {
    id: 'ch36-end',
    title: '潮汐还是岸 · 章末',
    subtitle: '潮汐贴上皮肤的岸',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch36-end.png'),
    video: cgAsset('/videos/cg/cg-ch36-end.webm'),
    storyHint: '第36章结尾',
  },
  {
    id: 'ch37-end',
    title: '黎明 · 章末',
    subtitle: '黎明潮间带的赤足',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch37-end.png'),
    video: cgAsset('/videos/cg/cg-ch37-end.webm'),
    storyHint: '第37章结尾',
  },
  {
    id: 'ch38-end',
    title: '潮间带 · 章末',
    subtitle: '礁石上并肩的影子',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch38-end.png'),
    video: cgAsset('/videos/cg/cg-ch38-end.webm'),
    storyHint: '第38章结尾',
  },
  {
    id: 'ch39-end',
    title: '假装平常 · 章末',
    subtitle: '假装平常时多停的半秒',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch39-end.png'),
    video: cgAsset('/videos/cg/cg-ch39-end.webm'),
    storyHint: '第39章结尾',
  },
  {
    id: 'ch40-end',
    title: '客人的眼光 · 章末',
    subtitle: '擦杯指节泛白的紧张',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch40-end.png'),
    video: cgAsset('/videos/cg/cg-ch40-end.webm'),
    storyHint: '第40章结尾',
  },
  {
    id: 'ch41-end',
    title: '备用钥匙 · 章末',
    subtitle: '钥匙递出时的耳根红',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch41-end.png'),
    video: cgAsset('/videos/cg/cg-ch41-end.webm'),
    storyHint: '第41章结尾',
  },
  {
    id: 'ch42-end',
    title: '买家皮鞋 · 章末',
    subtitle: '铺子灯光里的去留',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch42-end.png'),
    video: cgAsset('/videos/cg/cg-ch42-end.webm'),
    storyHint: '第42章结尾',
  },
  {
    id: 'ch43-end',
    title: '街角 · 章末',
    subtitle: '雨夜里紧握的手',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch43-end.png'),
    video: cgAsset('/videos/cg/cg-ch43-end.webm'),
    storyHint: '第43章结尾',
  },
  {
    id: 'ch44-end',
    title: '去留 · 章末',
    subtitle: '热汤上的答案',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch44-end.png'),
    video: cgAsset('/videos/cg/cg-ch44-end.webm'),
    storyHint: '第44章结尾',
  },
  {
    id: 'ch45-end',
    title: '为谁 · 章末',
    subtitle: '并肩清扫后的并肩',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch45-end.png'),
    video: cgAsset('/videos/cg/cg-ch45-end.webm'),
    storyHint: '第45章结尾',
  },
  {
    id: 'ch46-end',
    title: '联名的想象 · 章末',
    subtitle: '笑意藏不住的侧脸',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch46-end.png'),
    video: cgAsset('/videos/cg/cg-ch46-end.webm'),
    storyHint: '第46章结尾',
  },
  {
    id: 'ch47-end',
    title: '最后通牒 · 章末',
    subtitle: '店内重逢的暖',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch47-end.png'),
    video: cgAsset('/videos/cg/cg-ch47-end.webm'),
    storyHint: '第47章结尾',
  },
  {
    id: 'ch48-end',
    title: '潮声的门 · 章末',
    subtitle: '账本合上后的靠近',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch48-end.png'),
    video: cgAsset('/videos/cg/cg-ch48-end.webm'),
    storyHint: '第48章结尾',
  },
  {
    id: 'ch49-end',
    title: '十年不再等 · 章末',
    subtitle: '真笑落下的那一下',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch49-end.png'),
    video: cgAsset('/videos/cg/cg-ch49-end.webm'),
    storyHint: '第49章结尾',
  },
  {
    id: 'ch50-end',
    title: '分叉的岸 · 章末',
    subtitle: '潮间带上十指相扣',
    affectionRequired: 0,
    storyUnlock: true,
    image: cgAsset('/images/cg/cg-ch50-end.png'),
    video: cgAsset('/videos/cg/cg-ch50-end.webm'),
    storyHint: '第50章结尾',
  },
